In [1]:
import numpy as np
from syft.core.tensor.lazy_repeat_array import lazyrepeatarray

In [2]:
a = np.array((4, 0))

In [3]:
array1 = lazyrepeatarray(a, (4, 2))

In [4]:
array1.data

array([4, 0])

In [5]:
b = (np.random.random((2, 4)))
array1 @ b

<lazyrepeatarray data: [2.55344903 2.81981113 1.55585965 0.83052235] -> shape: (4, 4)>

In [6]:
array2 = lazyrepeatarray(2, (2, 5))

In [7]:
array1 @ array2

<lazyrepeatarray data: [[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]] -> shape: (4, 5)>

In [8]:
np.nonzero(array1.data)

(array([0]),)

In [9]:
array1.data.shape[0]

2

In [10]:
from scipy.sparse import coo_array

In [11]:
array1

<lazyrepeatarray data: [4 0] -> shape: (4, 2)>

In [12]:
array1.shape

(4, 2)

In [13]:
# row = np.indices(array1.shape).reshape(2, -1)[0]
# col = np.indices(array1.shape).reshape(2, -1)[1]
# data = np.repeat(array1.data, row.shape)
# sparse_array1 = coo_array((data, (row, col)))
# sparse_array1

In [14]:
row = np.indices(array2.shape).reshape(2, -1)[0]
col = np.indices(array2.shape).reshape(2, -1)[1]
data = np.repeat(array2.data, row.shape)
sparse_array2 = coo_array((data, (row, col)))
sparse_array2

<2x5 sparse array of type '<class 'numpy.int64'>'
	with 10 stored elements in COOrdinate format>

In [16]:
# out = sparse_array1.dot(sparse_array2)

In [17]:
# out.data

NameError: name 'out' is not defined

In [18]:
array1 @ array2

<lazyrepeatarray data: [[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]] -> shape: (4, 5)>

In [19]:
# s1 = lazyrepeatarray(2, (24076, 21779))
# s2 = lazyrepeatarray(4, (21779, 24076))
s1 = lazyrepeatarray(0, (1000, 1000))
s2 = lazyrepeatarray(4, (1000, 1000))

In [20]:
import time 

In [21]:
start = time.time()
s1 @ s2
end = time.time()

In [22]:
time_taken = end - start
time_taken

0.45892786979675293

In [23]:
row = np.indices(s1.shape).reshape(2, -1)[0]
col = np.indices(s1.shape).reshape(2, -1)[1]
data = np.repeat(s1.data, row.shape)
sparse_s1 = coo_array((data, (row, col)))

In [24]:
row = np.indices(s2.shape).reshape(2, -1)[0]
col = np.indices(s2.shape).reshape(2, -1)[1]
data = np.repeat(s2.data, row.shape)
sparse_s2 = coo_array((data, (row, col)))

In [25]:
start = time.time()
sparse_s1.dot(sparse_s2)
end = time.time()

In [26]:
time_taken = end - start
time_taken

1.0023181438446045